### ISSUE TITLE
Black screen/lockup on start

### ISSUE THREAD

**Issue by vpltd-peterm** [virtual-programming/overlord-linux#3]
We've heard several reports of this so far. The game will lockup at a black screen early on startup, and has to be force killed.

If you get this issue, please post here with your system details as described in the README.MD

**Comment by strycore** [comment]
If can confirm that. The game will work fine on the first launch then all further launches will result in a black screen.

```
System specs:
CPU: Intel Core i7-4790K
GPU: ASUS STRIX-GTX970 (Driver Version: 367.35)
RAM: Corsair 16GB DDR3 1600 Mhz
OS: Ubuntu 16.04 LTS
DM: Unity 7
```

**Comment by mmayfield1** [comment]
Same issue.

System specs:
CPU: AMD FX 8350
GPU: NVIDIA GTX 980
RAM: Corsair 16GB DDR3 1600 Mhz
OS: Fedora 23 64 Bit
DM: Mate

First launch is fine, all subsequent launches get black screen and require kill -9

**Comment by cberkenpas** [comment]
It seems for some people they're able to reboot and then it works on the first try? Unfortunately, I'm unable to test that right now. Otherwise, I appear to have the same issue on 2 systems:

Whenever I run strace -p<pid> against the './overlord.i386' process I see:
strace: Process 31587 attached
strace: [ Process PID=31587 runs in 32 bit mode. ]
futex(0x85de6a0, FUTEX_WAIT_PRIVATE, 2, NULL

I see a blackscreen if I attempt to run it in fullscreen mode, and in windowed mode, it seems the window doesn't repaint and will just show the contents of whatever windows were most recently over the Overlord window.

Overlord II seems to work just fine.

When using the standalone version from https://www.deliver2.com/, the game runs fine except for a consistent crash during a specific part at Heaven's Peak (which I'll report if I see the same behavior in the steam version once this issue is fixed).

Laptop specs:
CPU: Intel i7-6820HK
GPU: GTX 980M
RAM: 32GB
OS: KDE Neon (Ubuntu 16.04 flavor)

Desktop specs:
CPU: Intel i7-6900k
GPU: GTX 1080
RAM: 128GB
OS: KDE Neon (Ubuntu 16.04 flavor)

**Comment by leillo1975** [comment]
I have the same problem. If I launch the configuration window and do "Save and Play" the game works OK. 

My system Specs:
CPU: Intel i5-2500
GPU: GTX 950-2GB (367.35 driver)
RAM: 16GB DDR3
OS: Ubuntu 16.04 64bits

**Comment by cjxgm** [comment]
Same here that the game works fine on the first launch then all further launches result in a black screen.

```
System specs:
CPU: Intel Core i5-3230M
GPU: Intel HD Graphics 4400 (IvyBridge)
RAM: 4GB DDR3
OS: Arch Linux 2016-07-27
DM: GNOME 3.20
```

**Comment by cjxgm** [comment]
I figured out that
```
rm -rf ~/.local/share/vpltd/Overlord
```
solves the problem, but
```
rm -rf ~/.local/share/vpltd/Overlord/*
```
doesn't work.

**Comment by vpltd-peterm** [comment]
We should have a patch for this shortly..

**Comment by vpltd-peterm** [comment]
The game should shortly update to BuildID 1247517, which should fix the problem

**Comment by k4os77** [comment]
Fixed

**Comment by cberkenpas** [comment]
This is mostly fixed for me. In Steam I have "Overlord" and "Overlord: Raising Hell". The problem seems fixed for Overlord, but not Overlord: Raising Hell. Probably the it was forgotten to fixing Raising Hell too.

It seems running regular Overlord you have the Raising Hell content anyway.

I didn't get to test too thoroughly this morning as I had to head in to work, but it seems if you run Overlord with the configure options, then do save and play that Raising Hell works the first time.

I can't quite remember, but I think after running Raising Hell, regular Overlord won't work until you run it with configure first and do "save and play". But I was only able to test briefly and I can't remember for sure, so take this paragraph with a grain of salt.

**Comment by vpltd-peterm** [comment]
Overlord and Raising Hell use the same executable. Raising Hell is simply addon data for Overlord. The configuration is slightly odd on Steam due to how the original Windows version was set up.

In short, if you have Overlord + Raising Hell installed, you will always get Raising Hell no matter which one you launch.

**Comment by cberkenpas** [comment]
I figured that was mostly or entirely the case.

Testing again on my laptop at work, both work consistently every time. Looks like the issue is completely fixed for me too.

**Comment by vpltd-peterm** [comment]
Closing this as it seems completely resolved for all :)
